### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [holgern/py-scrypt#4]
Problem
---------
On aarch64, pip install py-scrypt builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install py-scrypt should download the wheels from pypi

@holgern, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by holgern** [comment]
@odidev, Can you check of the released aarch64 wheel is working correctly?

**Comment by holgern** [comment]
aarch64 builds have been added
