### ISSUE TITLE
missing gettimeofday.c in 0.8.19

### ISSUE THREAD

**Issue by jaant** [holgern/py-scrypt#8]
[scrypt-0.8.19.tar.gz](https://files.pythonhosted.org/packages/d2/e1/f2cf7a9d88865e7f030b8674d60343e0d3c511c9a929b2dfc894265df878/scrypt-0.8.19.tar.gz) does not include `scrypt-windows-stubs/gettimeofday.c` for some reason, causing the installation to fail on windows.

EDIT: probably because the `MANIFEST.in` only grabs `*.h` files from that dir.

**Comment by holgern** [comment]
Fixed in 0.8.20
